### ISSUE TITLE
deepseek-vl系列的微调支持 (finetune)

### ISSUE THREAD

**Issue by Jintao-Huang** [deepseek-ai/DeepSeek-VL#10]
ms-swift大模型训练框架已经支持了deepseek-vl系列模型的推理和微调～

最佳实践可以查看这里: 
https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/deepseek-vl%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md

**Comment by RERV** [comment]
Thank you for supporting DeepSeek-VL!

**Comment by soloice** [comment]
Can you kindly confirm [if swift can be used to finetune visual encoder](https://github.com/deepseek-ai/DeepSeek-VL/issues/6#issuecomment-1992731315)? If so, how? If now, what's the simplest way to support it?

**Comment by xs818818** [comment]
还有就是lora微调后怎么部署使用

**Comment by SinanAkkoyun** [comment]
@soloice Thank you very much for asking

**Comment by Jintao-Huang** [comment]
LoRA fine-tuning and merge-LoRA have been supported for both the visual encoder and aligner. 
Full parameter fine-tuning is also supported.
😊

**Comment by SinanAkkoyun** [comment]
I am super grateful for your work, thank you a lot!!! ❤️

**Comment by Ethanscuter** [comment]
最佳实践的link已经打不开了，可以重新给一个link吗？谢谢

**Comment by HugNature** [comment]
> 最佳实践的link已经打不开了，可以重新给一个link吗？谢谢
可以参考一下
https://mp.weixin.qq.com/s/SiVNGbe8M1k18YlVCZqLNA
