### ISSUE TITLE
About the preprocessor way in high and low input?

### ISSUE THREAD

**Issue by lucasjinreal** [deepseek-ai/DeepSeek-VL#17]
the SAM using different means compare to Siglip,

but from the code, the VLIChatProcessor are just using 1024 as size, imagenet_mean as input, this is right for SAM, but not right for siglip.

the processed tensors are directly sending to HybridTower without any further process.

Why doing this? Is the correct?

**Comment by TuuSiwei** [comment]
What's your opinion on this issue? I've found that some other works using dual vision encoders still employ different preprocessing

**Comment by Murasame-sway** [comment]
What's your opinion on this issue? I've found that some other works using dual vision encoders still employ different preprocessing
@lucasjinreal
