### ISSUE TITLE
Multi-image mixed input

### ISSUE THREAD

**Issue by TechxGenus** [deepseek-ai/DeepSeek-VL#20]
Does DeepSeek-VL series support input of multiple images? This doesn't seem to be stated in the paper, but `images` in the example script are `list`, which seems to be supported.

**Comment by jiezi4ai** [comment]
I have not yet dived into the code. But based on testing result,  it seems no. It could not suport multiple images QA

**Comment by DirtyKnightForVi** [comment]
> Does DeepSeek-VL series support input of multiple images? This doesn't seem to be stated in the paper, but `images` in the example script are `list`, which seems to be supported.

deepseek_vl/models/proccessing_vlm.py，find function called `apply_sft_template_for_multi_turn_prompts()`

**Comment by StevenLiuWen** [comment]
Hi, the model supports multiple images. Refer to https://huggingface.co/deepseek-ai/deepseek-vl-7b-chat/discussions/4 for the prompt example.

```python

conversation = [
    {
        "role": "User",
        "content": "Compare and contrast <image_placeholder> and <image_placeholder>.",
        "images": ["./data/1.png", "./data/2.jpg"]
    },
    {
        "role": "Assistant",
        "content": ""
    }
]
```

The first `<image_placeholder>` corresponds to "./data/1.png," while the second `<image_placeholder>` corresponds to "./data/2.png."

We will update the prompt example in README about the multiple images later.

**Comment by TechxGenus** [comment]
Thanks for your reply. Close this issue.
