### ISSUE TITLE
error when i run inference.py

### ISSUE THREAD

**Issue by Yangfan-96** [deepseek-ai/DeepSeek-VL#37]
Traceback (most recent call last):
  File "inference.py", line 56, in <module>
    outputs = vl_gpt.language_model.generate(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/transformers/generation/utils.py", line 1527, in generate
    result = self._greedy_search(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/transformers/generation/utils.py", line 2411, in _greedy_search
    outputs = self(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 1196, in forward
    outputs = self.model(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 990, in forward
    causal_mask = self._update_causal_mask(attention_mask, inputs_embeds, cache_position)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 1076, in _update_causal_mask
    causal_mask = torch.triu(causal_mask, diagonal=1)
RuntimeError: "triu_tril_cuda_template" not implemented for 'BFloat16'

**python=3.8**
accelerate                0.28.0
aiofiles                  23.2.1
altair                    5.2.0
annotated-types           0.6.0
anyio                     4.3.0
attrdict                  2.0.1
attrs                     23.2.0
Brotli                    1.0.9
certifi                   2024.2.2
charset-normalizer        2.0.4
click                     8.1.7
colorama                  0.4.5
contourpy                 1.1.1
cycler                    0.12.1
deepseek_vl               1.0.0       /app
einops                    0.7.0
exceptiongroup            1.2.0
fastapi                   0.110.0
ffmpy                     0.3.2
filelock                  3.13.1
fonttools                 4.50.0
fsspec                    2024.3.1
gmpy2                     2.1.2
gradio                    3.48.0
gradio_client             0.6.1
h11                       0.14.0
httpcore                  1.0.4
httpx                     0.27.0
huggingface-hub           0.22.0
idna                      3.4
importlib_metadata        7.1.0
importlib_resources       6.4.0
Jinja2                    3.1.3
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
latex2mathml              3.77.0
Markdown                  3.4.1
MarkupSafe                2.1.3
matplotlib                3.7.5
mdtex2html                1.3.0
mkl-fft                   1.3.8
mkl-random                1.2.4
mkl-service               2.4.0
mpmath                    1.3.0
networkx                  3.1
numpy                     1.24.3
orjson                    3.9.15
packaging                 24.0
pandas                    2.0.3
pillow                    10.2.0
pip                       23.3.1
pkgutil_resolve_name      1.3.10
psutil                    5.9.8
pydantic                  2.6.4
pydantic_core             2.16.3
pydub                     0.25.1
Pygments                  2.12.0
pyparsing                 3.1.2
pypinyin                  0.50.0
PySocks                   1.7.1
python-dateutil           2.9.0.post0
python-multipart          0.0.9
pytz                      2024.1
PyYAML                    6.0.1
referencing               0.34.0
regex                     2023.12.25
requests                  2.31.0
rpds-py                   0.18.0
safetensors               0.4.2
semantic-version          2.10.0
sentencepiece             0.1.96
setuptools                68.2.2
six                       1.16.0
sniffio                   1.3.1
starlette                 0.36.3
sympy                     1.12
tiktoken                  0.5.2
timm                      0.9.16
tokenizers                0.15.2
toolz                     0.12.1
torch                     2.0.1
torchaudio                2.0.2
torchvision               0.15.2
tqdm                      4.64.0
transformers              4.39.1
triton                    2.0.0
typing_extensions         4.9.0
tzdata                    2024.1
urllib3                   2.1.0
uvicorn                   0.29.0
websockets                11.0.3
wheel                     0.41.2
zipp                      3.18.1

**Comment by Yangfan-96** [comment]
pip install transformers==4.38.2

**Comment by Elfsong** [comment]
> pip install transformers==4.38.2
it works! Thank you!

**Comment by kharanshaik** [comment]
Worked, Thank you.!

**Comment by ArthurZucker** [comment]
https://github.com/meta-llama/llama3/issues/80 torch had breaking changes, that's the problem, not transformers

**Comment by mliuby** [comment]
> pip install transformers==4.38.2

Thanks! It works!!

**Comment by irisguoyf** [comment]
upgrade to torch 2.2.2 and  transformers  4.41.2 can solve this problem.
