### ISSUE TITLE
模型重复输出最后一句话，是什么原因呢，有办法能解决吗

### ISSUE THREAD

**Issue by Yangfan-96** [deepseek-ai/DeepSeek-VL#40]
User: <image_placeholder>描述这张图片

Assistant: 这张图片捕捉了自动驾驶汽车在城市街道上导航的瞬间。汽车是图片的中心焦点，位于画面中央，正朝着画面的右侧移动。它正在行驶的街道上标有黄色线条，表明了它的路径。

在汽车的两侧，可以看到两个数字标记。左边的标记显示了汽车的速度，而右边的标记显示了汽车的距离。这些标记为汽车提供了方向和距离的清晰指示。

在汽车的右侧，有一个蓝色的图标。这个图标可能代表一个特定的功能或设置，如转向辅助或车道保持辅助。

在汽车的左侧，有一个灰色的图标。这个图标可能代表一个特定的功能或设置，如自动泊车或自动变道辅助。

在汽车的上方，有一个黄色的图标。这个图标可能代表一个特定的功能或设置，如自动变道辅助或车道保持辅助。

在汽车的上方，有一个灰色的图标。这个图标可能代表一个特定的功能或设置，如自动泊车或自动变道辅助。

在汽车的上方，有一个灰色的图标。这个图标可能代表一个特定的功能或设置，如自动泊车或自动变道辅助。

在汽车的上方，有一个灰色的图标。这个图标可能代表一个特定的功能或设置，如自动泊车或自动变道辅助。

在汽车的上方，有一个灰色的图标。这个图标可能代表一个特定的功能或设置，如自动泊车或自动变道辅助。

在汽车的上方，有一个灰色的图标。这个图标可能代表一个特定的功能或设置，如自动泊车或自动变道辅助。

在汽车的上方，有一个灰色的图标。这个图标可能代表一个特定的功能或设置，如自动泊车或自动变道辅助。

在汽车的上方，有一个灰色的图标。这个图标可能代表一个特定的功能或设置，如自动泊车或自动变道辅助。

在汽车的上方，有一个灰色的图标。这个图标可能代表一个特定的功能或设置，如自动泊车或自动变道辅助。

在汽车的上方，有一个灰色的图标。这个图标可能代表一个特定的功能或设置，如自动泊车或自动变道辅助。

在汽车的上方，有一个灰色的图标。这个图标可能代表一个特定的功能或设置，如自动泊车或自动变道

**Comment by StevenLiuWen** [comment]
你是跑inference.py的结果吗，这个只是最简单的接口调用，生成的时候没有设置repetition_penalty参数抑制重复，你可以先跑一下cli_chat.py模式，里面设置了repetition_penalty参数，https://github.com/deepseek-ai/DeepSeek-VL/blob/main/cli_chat.py#L202
