### ISSUE TITLE
请问什么时候可以开源微调代码

### ISSUE THREAD

**Issue by cdxzyc** [deepseek-ai/DeepSeek-VL#9]

**Comment by RERV** [comment]
Hi, thank you for your interest. We are currently busy iterating DeepSeek-VL. The community has already started supporting DeepSeek-VL (#10 ). Have fun!
https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/deepseek-vl%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md
